# Generated by Django 5.2 on 2025-04-24 08:30

import apps.v1.shared.validators
import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField(validators=[apps.v1.shared.validators.clean_future_date])),
                ('lesson_start_time', models.TimeField(default='14:00')),
                ('lesson_duration', models.PositiveIntegerField(default=90)),
                ('end_date', models.DateField(blank=True, null=True, validators=[apps.v1.shared.validators.clean_past_date])),
                ('is_active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('lesson_days', models.ManyToManyField(blank=True, to='courses.weekday')),
                ('students', models.ManyToManyField(blank=True, limit_choices_to={'role__in': ['student', 'teacher']}, related_name='enrolled_groups', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='studentgroups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
