# Generated by Django 5.2 on 2025-04-20 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('student', 'Student'), ('parents', 'Parents'), ('admin', 'Admin')], default='admin', max_length=20),
        ),
    ]
