# Generated by Django 5.2 on 2025-04-11 10:42

import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('day', models.CharField(choices=[('Monday', 'Dushanba'), ('Tuesday', 'Seshanba'), ('Wednesday', 'Chorshanba'), ('Thursday', 'Payshanba'), ('Friday', 'Juma'), ('Saturday', 'Shanba'), ('Sunday', 'Yakshanba')], max_length=30, unique=True)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=200, verbose_name='Kurs nomi')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='course_covers/')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Narxi')),
                ('start_date', models.DateField(verbose_name='Boshlanish sanasi')),
                ('lesson_start_time', models.TimeField(default='14:00', help_text='Har bir darsning boshlanish vaqti (soat:daqiqa)', verbose_name='Dars boshlanish vaqti')),
                ('lesson_duration', models.PositiveIntegerField(default=90, help_text='Har bir darsning davomiyligi daqiqalarda', verbose_name='Dars davomiyligi (daqiqa)')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Tugash sanasi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('students', models.ManyToManyField(blank=True, limit_choices_to={'role__in': ['student', 'teacher']}, related_name='enrolled_courses', to=settings.AUTH_USER_MODEL, verbose_name="O'quvchilar")),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='taught_courses', to=settings.AUTH_USER_MODEL, verbose_name="O'qituvchi")),
                ('lesson_days', models.ManyToManyField(blank=True, help_text="Dars bo'ladigan hafta kunlari", to='courses.weekday', verbose_name='Dars kunlari')),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': 'Kurslar',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('content', models.TextField(verbose_name='Mazmuni')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='Video havolasi')),
                ('duration', models.PositiveIntegerField(default=0, help_text='Daqiqalarda', verbose_name='Davomiyligi')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
                ('is_free', models.BooleanField(default=False, verbose_name='Bepul')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course', verbose_name='Kurs')),
            ],
            options={
                'verbose_name': 'Dars',
                'verbose_name_plural': 'Darslar',
                'ordering': ['order'],
                'unique_together': {('course', 'order')},
            },
        ),
        migrations.CreateModel(
            name='LessonAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('file', models.FileField(upload_to='lesson_attachments/', verbose_name='Fayl')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='courses.lesson', verbose_name='Dars')),
            ],
            options={
                'verbose_name': 'Dars materiali',
                'verbose_name_plural': 'Dars materiallari',
            },
        ),
    ]
