# Generated by Django 5.2 on 2025-04-11 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('deadline', models.DateTimeField(verbose_name='Topshirish muddati')),
                ('status', models.CharField(choices=[('assigned', 'Topshirilgan'), ('in_progress', 'Bajarilmoqda'), ('completed', 'Yakunlangan'), ('rejected', 'Rad etilgan'), ('accepted', 'Qabul qilingan')], default='assigned', max_length=20, verbose_name='Holati')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_tasks', to='courses.course', verbose_name='Kurs')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='individual_tasks', to='courses.lesson', verbose_name='Dars')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='individual_tasks', to=settings.AUTH_USER_MODEL, verbose_name="O'quvchi")),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name="O'qituvchi")),
            ],
            options={
                'verbose_name': 'Individual topshiriq',
                'verbose_name_plural': 'Individual topshiriqlar',
                'ordering': ['-created'],
                'unique_together': {('course', 'student', 'title')},
            },
        ),
    ]
