# Generated by Django 5.2 on 2025-04-20 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_lesson_options_alter_lesson_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='teacher',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='course',
            name='students',
        ),
    ]
