# Generated by Django 5.2 on 2025-04-20 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_rename_teacher_course_owner_remove_course_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='course',
            name='lesson_days',
        ),
        migrations.RemoveField(
            model_name='course',
            name='lesson_duration',
        ),
        migrations.RemoveField(
            model_name='course',
            name='lesson_start_time',
        ),
        migrations.RemoveField(
            model_name='course',
            name='start_date',
        ),
    ]
