# Generated by Django 5.2 on 2025-04-11 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_individualtask_status_lesson_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='duration',
        ),
    ]
