# Generated by Django 5.2 on 2025-04-11 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_lesson_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='is_free',
        ),
    ]
