# Generated by Django 5.2 on 2025-04-20 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_lesson_options_alter_lesson_unique_together_and_more'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentgroup',
            name='direction',
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='courses.course'),
            preserve_default=False,
        ),
    ]
