# Generated by Django 5.2 on 2025-04-20 07:43

import shared.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_course_end_date_remove_course_lesson_days_and_more'),
        ('groups', '0003_studentgroup_students_alter_studentgroup_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgroup',
            name='end_date',
            field=models.DateField(blank=True, null=True, validators=[shared.validators.clean_future_date]),
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='lesson_days',
            field=models.ManyToManyField(blank=True, to='courses.weekday'),
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='lesson_duration',
            field=models.PositiveIntegerField(default=90),
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='lesson_start_time',
            field=models.TimeField(default='14:00'),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='start_date',
            field=models.DateField(validators=[shared.validators.clean_future_date]),
        ),
    ]
