# Generated by Django 5.2 on 2025-04-20 14:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_alter_studentgroup_students'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgroup',
            name='students',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role__in': ['student', 'teacher']}, related_name='enrolled_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
