# Generated by Django 5.2 on 2025-04-17 12:05

import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('is_draft', models.BooleanField(default=True)),
                ('message', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, null=True)),
                ('scheduled_at', models.DateTimeField()),
                ('category', models.CharField(choices=[('imtihon', 'Imtihon'), ('guruh', 'Guruhga qo‘shilganlik'), ('uyga_vazifa', 'Uyga vazifa'), ('dars', 'Darsni baholang')], max_length=20)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('new_exams', models.BooleanField(default=True, verbose_name='New exams')),
                ('exam_announcement', models.BooleanField(default=True, verbose_name='Exam announcement')),
                ('exam_due_soon', models.BooleanField(default=True, verbose_name='Exam due soon')),
                ('new_homework', models.BooleanField(default=True, verbose_name='New homework')),
                ('homework_reviewed', models.BooleanField(default=True, verbose_name='Homework reviewed')),
                ('homework_due_soon', models.BooleanField(default=True, verbose_name='Homework due soon')),
                ('joined_group', models.BooleanField(default=True, verbose_name='Joined a group')),
                ('removed_from_group', models.BooleanField(default=True, verbose_name='Removed from group')),
                ('xp_awarded', models.BooleanField(default=True, verbose_name='XP or Silver awarded')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
